name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build APK and Create Release
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установить JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг 3: Создать папку для сертификатов
      - name: Setup certificates from Secrets
        run: |
          mkdir -p app/src/main/assets/certs
          echo "${{ secrets.CLIENT_CRT_BASE64 }}" | base64 --decode > app/src/main/assets/certs/client.crt
          echo "${{ secrets.CLIENT_KEY_BASE64 }}" | base64 --decode > app/src/main/assets/certs/client.key
          ls -la app/src/main/assets/certs/

      # Шаг 4: Собрать APK с кастомным BASE_URL
      - name: Build APK with custom BASE_URL
        run: |
          ./gradlew assembleDebug -PbaseUrl="${{ secrets.BASE_URL }}"

      # Шаг 5: Получить информацию о версии и безопасно показать BASE_URL
      - name: Get version info
        id: version
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT
          
          # Безопасно показываем только первые символы BASE_URL
          BASE_URL="${{ secrets.BASE_URL }}"
          if [ -n "$BASE_URL" ]; then
            BASE_URL_PREVIEW=$(echo "$BASE_URL" | cut -c1-15)
            echo "BASE_URL_PREVIEW=${BASE_URL_PREVIEW}..." >> $GITHUB_OUTPUT
          else
            echo "BASE_URL_PREVIEW=not_set" >> $GITHUB_OUTPUT
          fi

      # Шаг 6: Создать Release и загрузить APK
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 TestBioProcessor ${{ github.ref_name }}
            
            ### 📦 Информация о сборке:
            - Версия: **${{ github.ref_name }}**
            - API URL: `${{ steps.version.outputs.BASE_URL_PREVIEW }}`
            - Коммит: ${{ steps.version.outputs.SHORT_SHA }}
            - Собрано: ${{ steps.version.outputs.DATE }}
            - Сертификаты: Загружены из Secrets 🔐
            
            ### 📱 Установка:
            1. Скачайте APK файл ниже
            2. Разрешите установку из неизвестных источников
            3. Установите приложение
            
            ### 🔒 Безопасность:
            - mTLS аутентификация включена
            - Сертификаты защищены GitHub Secrets
            - Автоматическая сборка
            
            ---
            *Собрано автоматически с GitHub Actions*
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/debug/app-debug.apk
          asset_name: TestBioProcessor-${{ github.ref_name }}.apk

      # Шаг 7: Уведомление об успехе
      - name: Success Notification
        if: success()
        run: |
          echo "✅ APK УСПЕШНО СОБРАН И ОПУБЛИКОВАН!"
          echo "---"
          echo "📱 Приложение: TestBioProcessor"
          echo "🏷️ Версия: ${{ github.ref_name }}"
          echo "🔗 API URL: ${{ steps.version.outputs.BASE_URL_PREVIEW }}"
          echo "📅 Собрано: ${{ steps.version.outputs.DATE }}"
          echo "📦 Файл: TestBioProcessor-${{ github.ref_name }}.apk"
          echo "---"
          echo "🎉 Пользователи могут скачать APK из раздела Releases!"